openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Musics-end-point
    description: Gestion des quotes
paths:
  /music:
    get:
      tags:
        - Music-end-point
      summary: Obtient une liste de toutes les musics
      operationId: getMusics
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Music'
        '404':
          description: Not Found
components:
  schemas:
    Music:
      description: toutes les caractéristiques d'une music
      type: object
      properties:
        author:
          description: nom de l'auteur
          type: string
        title:
          description: titre de la music
          type: string
        id:
          description: numéro auto-incrémenté de la citation
          type: integer
          format: int32
      title: Music