insert into artists values (1, 'Rick Astley', 'Classic');
insert into artists values (2, 'Justin Timberlake', 'Classic');
insert into artists values (3, 'Anna Kendrick', 'Rock');
insert into artists values (4, 'Zooey Deschanel', 'Classic');
insert into musics values (1, 'Never gonna give you up', 1);
insert into musics values (2, 'Can''t Stop the Feeling!', 2);
insert into musics values (3, 'The Sound Of Silence', 3);
insert into musics values (4, 'Hello', 4);
insert into playlists values (1, 'Fun playlist');
insert into playlists values (2, 'Troll playlist');
insert into playlists values (3, 'No idea what i am doing');
insert into playlist_music values (1, 1);
insert into playlist_music values (1, 2);
insert into playlist_music values (2, 2);
insert into playlist_music values (2, 3);
insert into playlist_music values (2, 4);
insert into playlist_music values (3, 4);