openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Quotes-end-point
    description: Gestion des quotes
  - name: Musics-end-point
    description: Gestion des musics
  - name: Playlists-end-point
    description: Gestion des playlists
paths:
  /musics:
    get:
      tags:
        - Musics-end-point
      summary: Obtient une liste de toute les musics
      operationId: getMusics
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Music'
        '404':
          description: Not Found
  /playlists:
    get:
      tags:
        - Playlists-end-point
      summary: Obtient une liste de toute les playlists
      operationId: getPlaylists
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Playlist'
        '404':
          description: Not Found
  /quotes:
    get:
      tags:
        - Quotes-end-point
      summary: Obtient une liste de toutes les quotes
      operationId: getQuotes
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: Not Found
    post:
      tags:
        - Quotes-end-point
      summary: Ajoute une nouvelle quote
      operationId: addQuote
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Quote'
      responses:
        '201':
          description: quote crée
          headers:
            Location:
              description: URL de la quote crée
              schema:
                type: string
                format: uri
  /quotes/{id}:
    get:
      tags:
        - Quotes-end-point
      summary: Obtient une quote
      operationId: getQuote
      parameters:
        - name: id
          in: path
          description: numéro de la quote à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    Quote:
      description: toutes les caractéristiques d'une quote
      type: object
      properties:
        author:
          description: nom de l'auteur
          type: string
        citation:
          description: phrase de la citation
          type: string
        id:
          description: numéro auto-incrémenté de la citation
          type: integer
          format: int32
      title: Quote
    Music:
      description: toutes les caractéristiques d'une music
      type: object
      properties:
        author:
          description: nom de l'auteur
          type: string
        title:
          description: titre de la music
          type: string
        id:
          description: numéro auto-incrémenté de la music
          type: integer
          format: int32
      title: Music
    Playlist:
      description: toutes les caractéristiques d'une playlist
      type: object
      properties:
        name:
          description: nom de la playlist
          type: string
        musics:
          description: musics de la playlist
          type: array
          items:
            $ref: "#/components/schemas/Music"
        id:
          description: numéro auto-incrémenté de la person
          type: integer
          format: int32
      title: Playlist